package config

const GET_CONFIG_PERIOD_IN_SECS = 5 * 60

const APPLICATION_STATUS_PUBLISH_PERIOD_IN_SECS = 1 * 60

const DEFAULT_EXPIRY_TIME_IN_SECS = 1800
const MAX_EXPIRY_TIME_IN_SECS = 86400

const DEFAULT_EXPIRY_COUNT = 50
const MAX_EXPIRY_COUNT = 1000

const BP_MONITOR_INTERVAL_SECONDS = 10

const SLEEP_BEFORE_SENDING_INIT_REQUEST_SECONDS = 2
